import {
  AtSign,
  Bot,
  Briefcase,
  Calendar,
  Camera,
  ExternalLink,
  FileText,
  Film,
  FolderOpen,
  Globe,
  Image as ImageIcon,
  Layers,
  Link as LinkIcon,
  Mail,
  MessageCircle,
  Megaphone,
  Music,
  Palette,
  Play,
  Send,
  ShoppingBag,
  Sparkles,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const QUICK_LINK_ICON_MAP: Record<string, LucideIcon> = {
  AtSign,
  Bot,
  Briefcase,
  Calendar,
  Camera,
  ExternalLink,
  FileText,
  Film,
  FolderOpen,
  Globe,
  Image: ImageIcon,
  Layers,
  Link: LinkIcon,
  Mail,
  MessageCircle,
  Megaphone,
  Music,
  Palette,
  Play,
  Send,
  ShoppingBag,
  Sparkles,
  Video,
  Zap,
  // Aliases para que los íconos "de marca" sigan resolviendo a algo razonable
  // (lucide-react v1.x no incluye Instagram/Facebook/Linkedin/Twitter/Youtube).
  Instagram: Camera,
  Facebook: Globe,
  Linkedin: Briefcase,
  Twitter: AtSign,
  Youtube: Play,
};

export const QUICK_LINK_ICONS: { value: string; label: string }[] = [
  { value: "Link", label: "🔗 Link" },
  { value: "Globe", label: "🌐 Web / Facebook" },
  { value: "Camera", label: "📷 Instagram / Foto" },
  { value: "AtSign", label: "🐦 Twitter / X / @" },
  { value: "Briefcase", label: "💼 LinkedIn / Trabajo" },
  { value: "Play", label: "▶ YouTube / Play" },
  { value: "Music", label: "🎵 TikTok / Música" },
  { value: "Video", label: "🎬 Video" },
  { value: "Film", label: "🎞 Film" },
  { value: "FolderOpen", label: "📁 Drive / Carpeta" },
  { value: "FileText", label: "📄 Documento" },
  { value: "Image", label: "🖼 Imagen" },
  { value: "Palette", label: "🎨 Diseño / Canva" },
  { value: "Bot", label: "🤖 Bot / Botly" },
  { value: "Megaphone", label: "📢 Ads / Anuncios" },
  { value: "Mail", label: "📧 Mail" },
  { value: "MessageCircle", label: "💬 Mensajes" },
  { value: "Send", label: "📨 Enviar" },
  { value: "Calendar", label: "📅 Calendario" },
  { value: "ShoppingBag", label: "🛍 E-commerce" },
  { value: "Sparkles", label: "✨ Otros" },
  { value: "Zap", label: "⚡ Rápido" },
  { value: "Layers", label: "🧱 Plataforma" },
  { value: "ExternalLink", label: "↗ Externo" },
];

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return LinkIcon;
  return QUICK_LINK_ICON_MAP[name] ?? LinkIcon;
}
