import {
  Bot,
  Briefcase,
  Calendar,
  ExternalLink,
  Facebook,
  FileText,
  Film,
  FolderOpen,
  Globe,
  Image as ImageIcon,
  Instagram,
  Layers,
  Link as LinkIcon,
  Linkedin,
  Mail,
  MessageCircle,
  Megaphone,
  Music,
  Palette,
  Send,
  ShoppingBag,
  Sparkles,
  Twitter,
  Video,
  Youtube,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const QUICK_LINK_ICON_MAP: Record<string, LucideIcon> = {
  Bot,
  Briefcase,
  Calendar,
  ExternalLink,
  Facebook,
  FileText,
  Film,
  FolderOpen,
  Globe,
  Image: ImageIcon,
  Instagram,
  Layers,
  Link: LinkIcon,
  Linkedin,
  Mail,
  MessageCircle,
  Megaphone,
  Music,
  Palette,
  Send,
  ShoppingBag,
  Sparkles,
  Twitter,
  Video,
  Youtube,
  Zap,
};

export const QUICK_LINK_ICONS: { value: string; label: string }[] = [
  { value: "Link", label: "🔗 Link" },
  { value: "Globe", label: "🌐 Web" },
  { value: "Instagram", label: "📷 Instagram" },
  { value: "Facebook", label: "📘 Facebook" },
  { value: "Linkedin", label: "💼 LinkedIn" },
  { value: "Twitter", label: "🐦 Twitter/X" },
  { value: "Youtube", label: "📺 YouTube" },
  { value: "Music", label: "🎵 TikTok / Música" },
  { value: "Video", label: "🎬 Video" },
  { value: "Film", label: "🎞 Film" },
  { value: "FolderOpen", label: "📁 Drive / Carpeta" },
  { value: "FileText", label: "📄 Documento" },
  { value: "Image", label: "🖼 Imagen" },
  { value: "Palette", label: "🎨 Diseño / Canva" },
  { value: "Bot", label: "🤖 Bot / Botly" },
  { value: "Megaphone", label: "📢 Ads / Anuncios" },
  { value: "Mail", label: "📧 Mail" },
  { value: "MessageCircle", label: "💬 Mensajes" },
  { value: "Send", label: "📨 Enviar" },
  { value: "Calendar", label: "📅 Calendario" },
  { value: "Briefcase", label: "💼 Trabajo" },
  { value: "ShoppingBag", label: "🛍 E-commerce" },
  { value: "Sparkles", label: "✨ Otros" },
  { value: "Zap", label: "⚡ Rápido" },
  { value: "Layers", label: "🧱 Plataforma" },
  { value: "ExternalLink", label: "↗ Externo" },
];

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return LinkIcon;
  return QUICK_LINK_ICON_MAP[name] ?? LinkIcon;
}
